# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='css_class',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
