# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0002_goodstype_css_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='img_show',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
