# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_detail', models.CharField(max_length=50)),
                ('tel_no', models.CharField(max_length=20)),
                ('site_cid', models.CharField(max_length=15)),
                ('site_str', models.CharField(max_length=200)),
                ('site_post', models.IntegerField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='dfuser',
            name='u_password',
            field=models.CharField(max_length=40),
        ),
        migrations.AddField(
            model_name='usersite',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.DfUser'),
        ),
    ]
