# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0002_auto_20170601_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersite',
            name='site_post',
            field=models.IntegerField(),
        ),
    ]
