# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0003_auto_20170601_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('birth', models.DateField()),
                ('nike_name', models.CharField(max_length=30)),
                ('last_sign_in', models.DateTimeField(auto_now=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('is_del', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='dfuser',
            name='is_del',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersite',
            name='is_del',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersite',
            name='set_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='df_user.DfUser'),
        ),
    ]
